Fix/sizing #10
hack4bengal/s3 pull request #15
Opened 2023-10-22 07:09 UTC by Muhammad-Shahid-Jamal

# Screen Shot
<img width="532" alt="Screenshot 2023-10-22 at 12 02 43 PM" src="https://github.com/hack4bengal/s3/assets/26340344/e5079437-1e7d-4b82-931c-bb510aee3eaf">

### Changes
- [x] padding and margin are the same as other sections
- [x] follow coding standards to do it.
- [x] package-lock.json file added to gitignore
- [x] pnpm-lock.yaml file added to gitignore   
- [x] unused import removed

2023-10-22 09:21 UTC, tamalCodes requested changes

2023-10-22 09:21 UTC, tamalCodes commented on .gitignore
> +package-lock.json
Please revert this change.

2023-10-22 09:21 UTC, tamalCodes commented on src/sections/ThemesSection/ThemesSection.jsx
> +      <div className="h4b_about_main">
As of the issue mentioned i don't think we might be needing framer motion's tool to get it done, i guess we can revert this to have a normal div in place.

2023-10-22 16:16 UTC, Muhammad-Shahid-Jamal reviewed
I have reverted gitignore and replaced simple div

2023-10-23 05:16 UTC, tamalCodes approved these changes
Great work, thanks for making the changes !

2023-10-23 05:17 UTC, merged