[FEATURE] Adding vite to the existing app #13
hack4bengal/s3 pull request #27
Opened 2023-10-24 06:36 UTC by sayakongit

## Description

This pull request migrates the current Create-React-App to Vite for the better performance of the site.

## Related Issue(s)

Fixes #13

## Changes Made

1. Installed vite and vite plugins
2. Removed react-scripts from `package.json` and added vite scripts instead.
3. Added `vite.config.js` file
4. Changed `.js` files to `.jsx`
5. Removed `%PUBLIC_URL%` in `index.html`
6. Fixed a import warning in [InfiniteCarousel.css](https://github.com/hack4bengal/s3/compare/main...sayakongit:s3:cra-to-vite?expand=1#diff-0593d1302fdc65f19e21c06f4e627b0e565f6b843e34a36ade4f753d8d3096aa)

2023-10-25 06:42 UTC, tamalCodes requested changes

2023-10-25 06:42 UTC, tamalCodes commented on package.json
> +    "start": "vite",
```suggestion
    "dev": "vite --port 3000",
```

2023-10-25 15:18 UTC, tamalCodes commented
@imanishbarnwal , take a look at the changes here, I guess this would require us to change the vercel settings from `npm start` to `npm run build` ?

Also @sayakongit , please fix the conflicts.

2023-10-25 15:34 UTC, sayakongit commented
@tamalCodes Fixed the conflicts! Can you check once now?

2023-10-26 14:51 UTC, sayakongit commented
@tamalCodes Can you please look into this and let me know if any more changes are required?

2023-10-26 18:25 UTC, merged