Issues template branch
hack4bengal/s3 pull request #33
Opened 2023-10-25 14:28 UTC by rajdeepbuilds

Created the bug issue report template

2023-10-26 18:51 UTC, tamalCodes commented
Hi @rajdeepbuilds , please also add it for Features, Docs, and Others.
You can take reference from [Milan/.github/ISSUE_TEMPLATE](https://github.com/MilanCommunity/Milan/tree/main/.github/ISSUE_TEMPLATE) for the templates but do not just copy paste.

2023-10-27 12:32 UTC, rajdeepbuilds commented
@tamalCodes kindy help me da
Vercel- Authorization required to deploy 
This is the error i am getting.
Else i have updated the bugs,features,docs and others issue templates.

2023-10-27 12:35 UTC, rajdeepbuilds commented
also i have accidently named the docs template as browser template.

2023-10-29 11:23 UTC, tamalCodes requested changes

2023-10-29 11:23 UTC, tamalCodes commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +  ]
I previously said to not just copy paste. We donot have a label called `status: todo ⏳` or `🐞 bug`
Please fix these kind of things across the whole code. Use the current labels that we have, for example `bug`

2023-10-29 11:24 UTC, tamalCodes commented
You don't need to deploy anything. Just push the changes. 
If there is any error we will take care of that.

2023-11-01 05:31 UTC, rajdeepbuilds reviewed
@tamalCodes kindly check it now

2024-01-05 16:29 UTC, closed without merging