[ FIX ] : Accessibility is improved . Issue Number #48
hack4bengal/s3 pull request #51
Opened 2024-01-09 16:26 UTC by harith-hacky03

All alt tags are changed to the names given by the alt generator . 
Links are improved to give better accessibility.

2024-01-09 16:59 UTC, tamalCodes requested changes
I think the score can be improved more, it shows errors for links and images too. [Check out the report.](https://pagespeed.web.dev/analysis/https-s3-website-elzd1i1hz-h4b-2-vercel-app/im5kwudcy9?form_factor=desktop)

![image](https://github.com/hack4bengal/s3/assets/72851613/bea06535-477d-4f3d-b8a0-3229b6c1bede)

2024-01-09 16:59 UTC, tamalCodes commented on src/components/private/faq/FAQ.jsx
> +                  Join our Discord community for support in #🎫ticket-support
```suggestion
                  in #🎫ticket-support
```

2024-01-09 16:59 UTC, tamalCodes commented on src/components/shared/footer/Footer.jsx
> +          <img src={h4b} alt="a black and white logo" />
```suggestion
          <img src={h4b} alt="A black and white logo representing Hack4Bengal" />
```

2024-01-09 16:59 UTC, tamalCodes commented on src/components/shared/footer/Footer.jsx
> +            Contact us: {footerContent.mail.address}
I guess we can remove this as the previous line says `Email Us for more details`

2024-01-09 17:10 UTC, harith-hacky03 commented
@tamalCodes  Is it okay now?

2024-01-10 03:56 UTC, tamalCodes commented
> @tamalCodes Is it okay now?

Paste the latest deployed link in [this tester](https://pagespeed.web.dev/) and see the score. If there are any errors, try and fix it.

2024-01-10 08:53 UTC, harith-hacky03 commented
![ps](https://github.com/hack4bengal/s3/assets/108193091/42aedb02-e8e9-45e9-b422-d98161dea62a)

2024-01-10 13:51 UTC, harith-hacky03 commented
@tamalCodes with my experience if you want higher performance, accessibility and seo. The app needs to be in next js. It offers prefetching server side rendering and other advanced features. Thank you

2024-01-10 15:16 UTC, tamalCodes commented
Hi there @harith-hacky03 

Changing tech stacks is not a solution in my opinion either. There is no data to be prefetched. All the data you see are essentially static. Serving static resources doesn't need a much-advanced tech stack I guess.


IF you visit [this link](https://pagespeed.web.dev/analysis/https-s3-website-op0qkda8i-h4b-2-vercel-app/llezp39hjn?form_factor=desktop) you will see that it says 

- `Image elements do not have [alt] attributes` meaning the alt tags are missing in some cases.
- `Lists do not contain only <li> elements and script supporting elements (<script> and <template>).` meaning we have used bad elements inside the `ul`
- Some elements might not be keyboard focusable/missing proper aria-roles


A11y has nothing to do with the tech stack, it has more to do with the number of missing things that we have and should have been there. Anyway Thank you so much for the contribution if you think you are done with the PR, let me know I will merge it.

2024-01-10 16:08 UTC, closed without merging